apiVersion: v1
kind: Pod
metadata:
  labels:
    run: complex-pod
  name: complex-pod
spec:
  containers:
  - image: nginx
    name: complex-pod
    ports:
    - containerPort: 80
  initContainers:
  - name: setup
    image: busybox
    command: ['sh', '-c', "wget http://example.com/file.iso"]

  restartPolicy: Never
