apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  serviceAccountName: monitoring
  volumes:
  - name: secret-volume
    secret:
      secretName: ext-service-secret
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name:  My-container-mount
      mountPath:  /var/app/mnt
  volumes:
  - name: my-mount  
    hostPath | secretName | configMapName
      path:  /external-host
  