apiVersion: v1
kind: Pod
metadata:
  name: sidecar-containers-impl
spec:
  containers:
  - name: nginx
    image: nginx:1.17
    volumes:
      - name: nginx-log-mount
        mountPath: /var/log/nginx
  - name: sidecar-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do if [\ "$cat( /var/log/nginx/error.log | grep 'error') \" != \"\"]; then echo 'Error !'; fi' sleep 10; done"]
  volumeMounts:
  - name:  nginx-log-mount
    emptyDir: {}
    