kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: app-stack
  name: access-nginx
spec:
  ingress:
  - from:
    - podSelector:
         matchLabels:
           app: todo
           tier: backend
    ports:
    - protocol: TCP
      port: 3306

