apiVersion: v1
kind: Pod
metadata:
  labels:
    run: data-exchange
  name: data-exchange
spec:
  containers:
  - image: busybox
    name: main-app
    volumeMounts:
  	name: data-vol
        mountPath: /var/app/data
  - name: sidecar
    image: busybox
    command: [‘sh’, ‘-c’, ‘tail -f /input/output.log’]
    volumeMounts:
        name: sharedvol
        mountPath: /input
  volumes:
    name: sharedvol
    restartPolicy: Never
