apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: ext-service-secret
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/var/app"
