apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpine
  name: alpine
spec:
  containers:
  - image: alpine:3.12.0
    name: alpine1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10; done"]
    volumeMounts:
    - mountPath: /etc/a
      name: alpine-volume
  - image: alpine:3.12.0
    name: alpine2
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10; done"]
    volumeMounts:
    - mountPath: /etc/b
      name: alpine-volume
  volumes:
  - name: alpine-volume
    emptyDir: {}
