apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: logs-pvc
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/var/log/nginx"
          name: nginx-volume
