apiVersion: v1
kind: Pod
metadata:
  labels:
    run: custom-cmd
  name: custom-cmd
spec:
  containers:
  - image: busybox
    name: custom-cmd
    command: ["top-analyzer"]
    args: ["-all"]
  restartPolicy: Always
